### ISSUE TITLE
Lectures should consider the question of "how many sightings are enough"

### ISSUE THREAD

**Issue by jjrob** [DistanceDevelopment/spatial-workshops#21]
This is a practical problem that comes for many people, especially with rare animals like marine mammals, where surveying is very expensive.

* How many sightings are enough to fit a detection function? Buckland et al. (2001) 60-80 gets used a lot. Clarify the importance and meaning of that rule of thumb. Maybe mention your new paper.

* What do you do when you don't have enough? E.g. pool multiple species, use fewer covariates or none.

* How many sightings (and segments) are enough to fit a standard line transect density estimate (one with no regression model as the second stage)?

* How about a GAM?

* Should you manually limit the number of covariates in the GAM if you have a "small" number of sightings? Or can you throw them all in and rely on mgcv to sort it out?

This might be appropriate for the Advanced Topics section. Regardless, we definitely need to discuss it at some point.

**Comment by dill** [comment]
I've added some thoughts on this in e5e5927, under `xx-practical-advice.Rpres`.

@jjrob let me know what you think and if you want me to add other content.

**Comment by jjrob** [comment]
Some feedback on `xx-practical-advice.pdf`:

* Slide 18: Consider referencing the following two papers. The first tested different lengths of segments and found out (possibly just for their situation!) that it didn't matter. The second one tested different spatial resolution of covariates (different cell sizes) and concluded much the same thing (but again, could be specific to their situation).

Redfern J, Barlow J, Ballance L, Gerrodette T, Becker E (2008) Absence of scale dependence in dolphin–habitat models for the eastern tropical Pacific Ocean. Marine Ecology Progress Series 363: 1–14. doi:10.3354/meps07495

Becker E, Forney K, Ferguson M, Foley D, Smith R, Barlow J, et al. (2010) Comparing California Current cetacean–habitat models developed using in situ and remotely sensed sea surface temperature data. Marine Ecology Progress Series 413: 163–183. doi:10.3354/meps08696

I'm submitting this comment now for your consideration but leaving this assigned to myself so I can review it more later and possibly offer additional feedback.

**Comment by dill** [comment]
I looked through these two papers previously (they are in the bibliography, I was going to mention them while I was talking) -- I think that it's likely that these issues are domain/species dependent (or at least we don't have enough evidence at this point to believe that they aren't). The papers don't really give me enough information about these scale issues to understand what's happening in terms of comparing the resolution of covariates or segments. I think both also constrain the basis complexity, so that may also complicate things...

I wonder how much marine vs. terrestrial makes a difference. Given the dynamic nature of, say SST, perhaps there is so much going on that resolution change actually makes little difference in the model when compared to everything else?

**Comment by dill** [comment]
Okay, this should now be folded into the practical advice lecture.
