### ISSUE TITLE
Practical 7 Rmd contains flubber

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/spatial-workshops#54]
@dill 

ran all practicals on Podium computer

think you may have left some debris behind when editing practicals; specifically 7-simple-dsm.  Reference therein to image located in an image file 
lines 65-27 again lines 83-90  

also prac6 and prac8 contain bibliographic references e.g. @Smith2006 that are not properly rendered because .bib file is missing.  No errors caused, but render leaves the \cite strings untouched

finally prac10 succeeds but produces pages of Newton warnings when running var.prop()

**Comment by dill** [comment]
Thanks for spotting these.

I've fixed the debris issue -- that seems that I forgot to cross-update 
the repos on my machine.

References sorted out.

Newton iteration warnings actually are useful here because I want to 
show this kind of problem.

I'll regenerate the bookdown right now and upload once it's done.
